name: "Terraform"

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      TF_WORKSPACE:
        required: true
        type: string
      live-branch:
        required: false
        type: string
        default: "main"
    secrets:
      GOOGLE_CREDENTIALS:
        required: true

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:

  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: .github/actions/terraform
        with:
          working-directory: ${{ inputs.working-directory }}
          TF_WORKSPACE: ${{ inputs.TF_WORKSPACE }}
          live-branch: ${{ inputs.live-branch }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
